# GoReleaser configuration file
# https://goreleaser.com/

version: 2

# Build configuration
builds:
  - id: modix
    main: ./cmd/modix/main.go
    binary: modix
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    # Exclude Windows ARM64 for now as it's less common
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Archive configuration
archives:
  - id: modix
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - README_zh.md
      - CLAUDE.md
      - AGENTS.md

# Release configuration
release:
  github:
    owner: promacanthus
    name: modix
  draft: false
  replace: true
  name_template: 'Modix Release {{.Version}}'
  notes:
    template: |
      ## What's Changed
      {{ range .Commits -}}
      - {{ .Subject }} ({{ .FullCommit }}){{ end }}

# Changelog configuration
changelog:
  disable: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^refactor:'
      - '^chore:'
      - '^style:'
      - '^perf:'
      - '^ci:'
      - '^deps:'

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Signatures
signs:
  - artifacts: checksum
    cmd: cosign
    args: ["sign-blob", "--yes", "--key=cosign.key", "--output-file={{ .ArtifactName }}.sig", "{{ .Path }}"]
    signature: "{{ .ArtifactName }}.sig"
    env:
      - COSIGN_EXPERIMENTAL=1
    output: true

# Homebrew tap (optional)
brews:
  - name: modix
    repository:
      owner: promacanthus
      name: homebrew-tap
    commit_author:
      name: promacanthus
      email: promacanthus@outlook.com
    description: "CLI tool for managing and switching between multiple LLM backends and large language models"
    install: |
      bin.install "modix"
      # Install documentation
      prefix.install "README.md"
      prefix.install "README_zh.md"
      prefix.install "CLAUDE.md"
      prefix.install "AGENTS.md"

# Scoop bucket (optional)
scoop:
  bucket:
    owner: promacanthus
    name: scoop-bucket
  commit_author:
    name: promacanthus
    email: promacanthus@outlook.com
  description: "CLI tool for managing and switching between multiple LLM backends and large language models"

# Snap package (optional)
# snaps:
#   - name: modix
#     publish: true
#     description: "CLI tool for managing and switching between multiple LLM backends and large language models"
#     summary: "LLM backend management CLI tool"